<?php

namespace Database\Seeders;
use App\Models\Usuarios;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UsuariosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $usuario= new Usuarios();
        $usuario->clave = 'URS1';
        $usuario->nombre = 'Jimena';
        $usuario->app = 'Diaz';
        $usuario->apm = 'De Los Santos';
        $usuario->gen = 'F';
        $usuario->fn = '2003-02-24';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al222110707@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '1';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS2';
        $usuario->nombre = 'Jossue Alejandro';
        $usuario->app = 'Candelas';
        $usuario->apm = 'Hernandez';
        $usuario->gen = 'M';
        $usuario->fn = '2003-06-17';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al222110811@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '1';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS3';
        $usuario->nombre = 'Miguel Emmanuel';
        $usuario->app = 'Arriola';
        $usuario->apm = 'Ortega';
        $usuario->gen = 'M';
        $usuario->fn = '2003-05-01';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al222010230@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '1';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS4';
        $usuario->nombre = 'Juan Carlos';
        $usuario->app = 'Lopez';
        $usuario->apm = 'Alarcon';
        $usuario->gen = 'M';
        $usuario->fn = '1998-09-04';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al222220002@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '1';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS5';
        $usuario->nombre = 'Christopher Dan';
        $usuario->app = 'Zarate';
        $usuario->apm = 'Bedolla';
        $usuario->gen = 'M';
        $usuario->fn = '1999-12-05';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al222111400@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '1';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS6';
        $usuario->nombre = 'Carlos Eduardo';
        $usuario->app = 'Olvera';
        $usuario->apm = 'Aldama';
        $usuario->gen = 'M';
        $usuario->fn = '2003-12-30';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al222111275@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '1';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS7';
        $usuario->nombre = 'Eduardo';
        $usuario->app = 'Diaz';
        $usuario->apm = 'Perez';
        $usuario->gen = 'M';
        $usuario->fn = '1978-03-01';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al721594356@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS8';
        $usuario->nombre = 'Yanet';
        $usuario->app = 'De Los Santos';
        $usuario->apm = 'Gomez';
        $usuario->gen = 'F';
        $usuario->fn = '1980-06-25';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al64512379@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS9';
        $usuario->nombre = 'Leopoldo';
        $usuario->app = 'Diaz';
        $usuario->apm = 'Sanchez';
        $usuario->gen = 'M';
        $usuario->fn = '2000-05-05';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al315794685@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS10';
        $usuario->nombre = 'Jose';
        $usuario->app = 'Sanchez';
        $usuario->apm = 'Gomez';
        $usuario->gen = 'M';
        $usuario->fn = '1979-08-12';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al125789139@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS11';
        $usuario->nombre = 'Jose';
        $usuario->app = 'Sanchez';
        $usuario->apm = 'Gomez';
        $usuario->gen = 'M';
        $usuario->fn = '1979-08-12';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al125789135@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS12';
        $usuario->nombre = 'Ana';
        $usuario->app = 'Toriz';
        $usuario->apm = 'Diego';
        $usuario->gen = 'F';
        $usuario->fn = '1975-11-24';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al348971569@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS13';
        $usuario->nombre = 'Alexa';
        $usuario->app = 'Gonzalez';
        $usuario->apm = 'Camacho';
        $usuario->gen = 'F';
        $usuario->fn = '1999-04-09';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al798145632@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS14';
        $usuario->nombre = 'Pedro';
        $usuario->app = 'Peña';
        $usuario->apm = 'Santiago';
        $usuario->gen = 'M';
        $usuario->fn = '1990-10-23';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al348971566@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS15';
        $usuario->nombre = 'Laura';
        $usuario->app = 'Jimenez';
        $usuario->apm = 'Amaro';
        $usuario->gen = 'F';
        $usuario->fn = '1994-01-06';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al36987215689@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS16';
        $usuario->nombre = 'Ana';
        $usuario->app = 'Toriz';
        $usuario->apm = 'Diego';
        $usuario->gen = 'F';
        $usuario->fn = '1975-11-24';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al348971555@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS17';
        $usuario->nombre = 'Juan';
        $usuario->app = 'Alvarez';
        $usuario->apm = 'Andrade';
        $usuario->gen = 'M';
        $usuario->fn = '1983-04-16';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al927468126@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS18';
        $usuario->nombre = 'Emmanuel';
        $usuario->app = 'Benitez';
        $usuario->apm = 'Castillo';
        $usuario->gen = 'M';
        $usuario->fn = '1996-09-19';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al394172648@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS19';
        $usuario->nombre = 'Beningno';
        $usuario->app = 'Arenas';
        $usuario->apm = 'Sosa';
        $usuario->gen = 'M';
        $usuario->fn = '1983-08-18';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al973468521@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS20';
        $usuario->nombre = 'Aurora';
        $usuario->app = 'Cordova';
        $usuario->apm = 'Delgado';
        $usuario->gen = 'F';
        $usuario->fn = '1991-11-20';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al647215381@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS21';
        $usuario->nombre = 'Nancy';
        $usuario->app = 'Corona';
        $usuario->apm = 'Diaz';
        $usuario->gen = 'F';
        $usuario->fn = '1999-07-15';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al378416982@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS22';
        $usuario->nombre = 'Hilario';
        $usuario->app = 'Carmona';
        $usuario->apm = 'Peralta';
        $usuario->gen = 'M';
        $usuario->fn = '1985-02-21';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al378469125@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS23';
        $usuario->nombre = 'Aleberto';
        $usuario->app = 'Castillejos';
        $usuario->apm = 'De Los Santos';
        $usuario->gen = 'M';
        $usuario->fn = '1979-05-19';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al168743915@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS24';
        $usuario->nombre = 'Maria';
        $usuario->app = 'Esquivel';
        $usuario->apm = 'Tabaco';
        $usuario->gen = 'F';
        $usuario->fn = '1976-12-12';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al671384561@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS25';
        $usuario->nombre = 'Graciela';
        $usuario->app = 'Fuentes';
        $usuario->apm = 'Hurtado';
        $usuario->gen = 'F';
        $usuario->fn = '1992-08-26';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al843179546@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS26';
        $usuario->nombre = 'Gustavo';
        $usuario->app = 'Diaz';
        $usuario->apm = 'Diaz';
        $usuario->gen = 'M';
        $usuario->fn = '1999-07-19';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al456713695@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS27';
        $usuario->nombre = 'Rene';
        $usuario->app = 'Garcia';
        $usuario->apm = 'Mancio';
        $usuario->gen = 'M';
        $usuario->fn = '1979-02-14';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al456123745@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS28';
        $usuario->nombre = 'Omar';
        $usuario->app = 'Fernandez';
        $usuario->apm = 'Maya';
        $usuario->gen = 'M';
        $usuario->fn = '1986-04-05';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al469517843@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS29';
        $usuario->nombre = 'Graciela';
        $usuario->app = 'Fuentes';
        $usuario->apm = 'Estrada';
        $usuario->gen = 'F';
        $usuario->fn = '1994-09-17';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al762498124@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS30';
        $usuario->nombre = 'Norma';
        $usuario->app = 'Gonzalez';
        $usuario->apm = 'Garcia';
        $usuario->gen = 'F';
        $usuario->fn = '1999-10-21';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al274159634@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS31';
        $usuario->nombre = 'Virginia';
        $usuario->app = 'Guerrero';
        $usuario->apm = 'Delgado';
        $usuario->gen = 'F';
        $usuario->fn = '1990-06-17';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al761349852@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS32';
        $usuario->nombre = 'Jesus';
        $usuario->app = 'Guadarrama';
        $usuario->apm = 'Campos';
        $usuario->gen = 'M';
        $usuario->fn = '1979-07-01';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al651348751@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS33';
        $usuario->nombre = 'Miguel';
        $usuario->app = 'Hernandez';
        $usuario->apm = 'Vallejo';
        $usuario->gen = 'M';
        $usuario->fn = '1991-03-19';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al745351625@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS34';
        $usuario->nombre = 'Andrea';
        $usuario->app = 'Herrera';
        $usuario->apm = 'Zuñiga';
        $usuario->gen = 'F';
        $usuario->fn = '1998-10-12';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al349517642@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS35';
        $usuario->nombre = 'Raquel';
        $usuario->app = 'Lara';
        $usuario->apm = 'Fierro';
        $usuario->gen = 'F';
        $usuario->fn = '1980-06-20';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al984613744@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS36';
        $usuario->nombre = 'Alejandro';
        $usuario->app = 'Jasso';
        $usuario->apm = 'Marcial';
        $usuario->gen = 'M';
        $usuario->fn = '1998-04-13';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al547135468@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS37';
        $usuario->nombre = 'Jose de Jesus';
        $usuario->app = 'Martinez';
        $usuario->apm = 'De la Vega';
        $usuario->gen = 'M';
        $usuario->fn = '1978-06-15';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al246875133@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS38';
        $usuario->nombre = 'Brenda';
        $usuario->app = 'Ortiz';
        $usuario->apm = 'Acosta';
        $usuario->gen = 'F';
        $usuario->fn = '1996-07-04';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al231456789@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS39';
        $usuario->nombre = 'Luz';
        $usuario->app = 'Perez';
        $usuario->apm = 'Ramos';
        $usuario->gen = 'F';
        $usuario->fn = '1990-03-20';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al345781456@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS40';
        $usuario->nombre = 'Emilio';
        $usuario->app = 'Peñaloza';
        $usuario->apm = 'Hugo';
        $usuario->gen = 'M';
        $usuario->fn = '1996-04-23';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al451230784@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS41';
        $usuario->nombre = 'Ruben';
        $usuario->app = 'Romero';
        $usuario->apm = 'Aguilar';
        $usuario->gen = 'M';
        $usuario->fn = '1979-04-21';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al843516784@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS42';
        $usuario->nombre = 'Eva';
        $usuario->app = 'Reyes';
        $usuario->apm = 'Garcia';
        $usuario->gen = 'F';
        $usuario->fn = '1999-12-11';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al1034561027@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS43';
        $usuario->nombre = 'Jazmin';
        $usuario->app = 'Romero';
        $usuario->apm = 'Hernandez';
        $usuario->gen = 'F';
        $usuario->fn = '1998-12-24';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al213456741@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS44';
        $usuario->nombre = 'Francisco';
        $usuario->app = 'Reza';
        $usuario->apm = 'Tejada';
        $usuario->gen = 'M';
        $usuario->fn = '1990-04-23';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al144337784@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS45';
        $usuario->nombre = 'Alejandro';
        $usuario->app = 'Rosas';
        $usuario->apm = 'Escalona';
        $usuario->gen = 'M';
        $usuario->fn = '1996-10-09';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al999123484@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS46';
        $usuario->nombre = 'Graciela';
        $usuario->app = 'Velazquez';
        $usuario->apm = 'Huerta';
        $usuario->gen = 'F';
        $usuario->fn = '1996-02-23';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al666321584@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS47';
        $usuario->nombre = 'Guadalupe';
        $usuario->app = 'Velasquez';
        $usuario->apm = 'Cruz';
        $usuario->gen = 'F';
        $usuario->fn = '1993-05-18';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al888246187@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS48';
        $usuario->nombre = 'Maribel';
        $usuario->app = 'Rueda';
        $usuario->apm = 'Nava';
        $usuario->gen = 'F';
        $usuario->fn = '1997-09-08';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al444615789@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS49';
        $usuario->nombre = 'Enrique';
        $usuario->app = 'Diaz';
        $usuario->apm = 'Castillo';
        $usuario->gen = 'M';
        $usuario->fn = '1976-01-21';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al777156423@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS50';
        $usuario->nombre = 'Margarita';
        $usuario->app = 'Perez';
        $usuario->apm = 'Morales';
        $usuario->gen = 'F';
        $usuario->fn = '1975-11-24';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al555127845@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS51';
        $usuario->nombre = 'Roberto';
        $usuario->app = 'Camacho';
        $usuario->apm = 'Mendoza';
        $usuario->gen = 'M';
        $usuario->fn = '1980-03-24';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al333456178@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS52';
        $usuario->nombre = 'Juan Fernando';
        $usuario->app = 'Perez';
        $usuario->apm = 'del Corral';
        $usuario->gen = 'M';
        $usuario->fn = '1980-12-30';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al654447512@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS53';
        $usuario->nombre = 'Valentina';
        $usuario->app = 'Laverde';
        $usuario->apm = 'de la Rosa';
        $usuario->gen = 'F';
        $usuario->fn = '1990-06-21';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al647111999@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS54';
        $usuario->nombre = 'Oscar';
        $usuario->app = 'de la Renta';
        $usuario->apm = 'Peña';
        $usuario->gen = 'M';
        $usuario->fn = '1978-02-18';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al666771122@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS55';
        $usuario->nombre = 'Sara Teresa';
        $usuario->app = 'Sanchez';
        $usuario->apm = 'del Pilar';
        $usuario->gen = 'F';
        $usuario->fn = '1999-04-02';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al888445511@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS56';
        $usuario->nombre = 'Efrain';
        $usuario->app = 'de las Casas';
        $usuario->apm = 'Mejía';
        $usuario->gen = 'M';
        $usuario->fn = '1980-11-20';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al665511122@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS57';
        $usuario->nombre = 'Julieta';
        $usuario->app = 'Ponce';
        $usuario->apm = 'de León';
        $usuario->gen = 'F';
        $usuario->fn = '1995-06-17';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al998877666@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS58';
        $usuario->nombre = 'Martin';
        $usuario->app = 'de los Rios';
        $usuario->apm = 'Acosta';
        $usuario->gen = 'M';
        $usuario->fn = '1983-01-27';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al222222222@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS59';
        $usuario->nombre = 'Gabriela';
        $usuario->app = 'de la Pava';
        $usuario->apm = 'de la Torre';
        $usuario->gen = 'F';
        $usuario->fn = '1986-07-14';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al777446612@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS60';
        $usuario->nombre = 'Matias';
        $usuario->app = 'de Greiff';
        $usuario->apm = 'Rincón';
        $usuario->gen = 'M';
        $usuario->fn = '1988-10-13';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al321564888@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS61';
        $usuario->nombre = 'Manuela';
        $usuario->app = 'del Pino';
        $usuario->apm = 'Hincapié';
        $usuario->gen = 'F';
        $usuario->fn = '1984-09-20';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al215611447@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS62';
        $usuario->nombre = 'Sebastian';
        $usuario->app = 'del Campo';
        $usuario->apm = 'Yepes';
        $usuario->gen = 'M';
        $usuario->fn = '1997-07-13';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al621222444@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS63';
        $usuario->nombre = 'Sofia';
        $usuario->app = 'del Rio';
        $usuario->apm = 'Arango';
        $usuario->gen = 'F';
        $usuario->fn = '1988-10-27';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al555666111@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS64';
        $usuario->nombre = 'Ana';
        $usuario->app = 'de la Peña';
        $usuario->apm = 'Posada';
        $usuario->gen = 'F';
        $usuario->fn = '1981-04-16';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al999456122@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS65';
        $usuario->nombre = 'Monica';
        $usuario->app = 'de Ávalos';
        $usuario->apm = 'Mendoza';
        $usuario->gen = 'M';
        $usuario->fn = '1986-02-01';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al120354871@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS66';
        $usuario->nombre = 'Abel';
        $usuario->app = 'Ponce';
        $usuario->apm = 'Gonzalez';
        $usuario->gen = 'M';
        $usuario->fn = '1984-10-16';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al999445129@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS67';
        $usuario->nombre = 'Catalina';
        $usuario->app = 'Espadas';
        $usuario->apm = 'Lopez';
        $usuario->gen = 'F';
        $usuario->fn = '1999-04-14';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al777777771@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '3';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS68';
        $usuario->nombre = 'Gloria';
        $usuario->app = 'Ley';
        $usuario->apm = 'Ibarra';
        $usuario->gen = 'F';
        $usuario->fn = '1998-01-18';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al222244451@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '4';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS69';
        $usuario->nombre = 'Hector';
        $usuario->app = 'Cervantes';
        $usuario->apm = 'Ortiz';
        $usuario->gen = 'M';
        $usuario->fn = '1985-07-17';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'al555555555@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '5';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();

        $usuario= new Usuarios();
        $usuario->clave = 'URS70';
        $usuario->nombre = 'Admin';
        $usuario->app = 'Sistemas';
        $usuario->apm = 'UTVT';
        $usuario->gen = '';
        $usuario->fn = '2000-01-01';
        $usuario->academico = 'TSU Área Dasarrollo de Software Multiplataforma';
        $usuario->foto = 'cuervo.png';
        $usuario->email = 'admiuippe@gmail.com';
        $usuario->pass = '123456';
        $usuario->id_tipo = '2';
        $usuario->activo = '1';
        $usuario->id_registro = '1';
        $usuario->save();
      }
    }

